export const IPC_CHANNELS = {
  authLogin: 'auth.login',
  authLogout: 'auth.logout',
  authGetSession: 'auth.getSession',
  authMe: 'auth.me',
  authChangePassword: 'auth.changePassword',
  authCompleteResetPassword: 'auth.completeResetPassword',
  catalogHome: 'catalog.home',
  catalogSearch: 'catalog.search',
  extensionGetDetail: 'extension.getDetail',
  extensionGetVersions: 'extension.getVersions',
  extensionSetStar: 'extension.setStar',
  extensionGetMcpDefinition: 'extension.getMcpDefinition',
  extensionGetPluginDefinition: 'extension.getPluginDefinition',
  deviceGetInfo: 'device.getInfo',
  localGetStatus: 'local.getStatus',
  localGetOfflineState: 'local.getOfflineState',
  localEnqueueEvent: 'local.enqueueEvent',
  localListPendingEvents: 'local.listPendingEvents',
  localListLifecycle: 'local.listLifecycle',
  localScanInventory: 'local.scanInventory',
  localCleanup: 'local.cleanup',
  localSyncPending: 'local.syncPending',
  settingsGetLocalConfig: 'settings.getLocalConfig',
  settingsSaveLocalConfig: 'settings.saveLocalConfig',
  logsGetRecent: 'logs.getRecent',
  extensionInstall: 'extension.install',
  mcpConfigure: 'mcp.configure',
  mcpConnectionTest: 'mcp.connectionTest',
  pluginPrepare: 'plugin.prepare',
  publishUploadPackage: 'publish.uploadPackage',
  publishCreateSubmission: 'publish.createSubmission',
  publishListMine: 'publish.listMine',
  publishGetSubmission: 'publish.getSubmission',
  publishWithdraw: 'publish.withdraw',
  publishResubmit: 'publish.resubmit',
  notificationsList: 'notifications.list',
  notificationsRead: 'notifications.read',
  clientUpdateCheck: 'clientUpdate.check',
  clientUpdateGetPending: 'clientUpdate.getPending',
  clientUpdateConfirmDownload: 'clientUpdate.confirmDownload',
  clientUpdateCancel: 'clientUpdate.cancel',
  clientUpdateConfirmInstall: 'clientUpdate.confirmInstall'
} as const;

export type IpcChannel = typeof IPC_CHANNELS[keyof typeof IPC_CHANNELS];
export const ALLOWED_IPC_CHANNELS = Object.values(IPC_CHANNELS);
